//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBox
    {
        public CashBox()
        {
            this.CashBoxDetail = new HashSet<CashBoxDetail>();
        }
    
        public System.Guid Id { get; set; }
        public long CashNumber { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.Guid> IdUser { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> CloseTotal { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<CashBoxDetail> CashBoxDetail { get; set; }
    }
}
