//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxType
    {
        public CashBoxType()
        {
            this.CashBoxDetail = new HashSet<CashBoxDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Sign { get; set; }
    
        public virtual ICollection<CashBoxDetail> CashBoxDetail { get; set; }
    }
}
