//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationSystem
    {
        public System.Guid Id { get; set; }
        public int FiscalYear { get; set; }
        public System.DateTime OperationsInitDate { get; set; }
        public long AuthorizedBillingInit { get; set; }
        public long AuthorizedBillingEnd { get; set; }
        public Nullable<System.Guid> IdCountry { get; set; }
        public Nullable<System.Guid> IdCurrency { get; set; }
    }
}
