//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturandoEntities : DbContext
    {
        public FacturandoEntities()
            : base("name=FacturandoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Action { get; set; }
        public DbSet<Bill> Bill { get; set; }
        public DbSet<BillDetail> BillDetail { get; set; }
        public DbSet<BillTaxes> BillTaxes { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Inventory> Inventory { get; set; }
        public DbSet<InventoryClassification> InventoryClassification { get; set; }
        public DbSet<InventoryDetail> InventoryDetail { get; set; }
        public DbSet<InventoryLocation> InventoryLocation { get; set; }
        public DbSet<InventoryType> InventoryType { get; set; }
        public DbSet<Module> Module { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Remission> Remission { get; set; }
        public DbSet<RemissionDetail> RemissionDetail { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolAction> RolAction { get; set; }
        public DbSet<RolModule> RolModule { get; set; }
        public DbSet<Tax> Tax { get; set; }
        public DbSet<UnitMeasure> UnitMeasure { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserRol> UserRol { get; set; }
        public DbSet<IdentificacionType> IdentificacionType { get; set; }
        public DbSet<ConfigurationSystem> ConfigurationSystem { get; set; }
    }
}
