//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.InventoryDetail = new HashSet<InventoryDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdProduct { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> LastSalePrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<InventoryDetail> InventoryDetail { get; set; }
    }
}
