//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadInventory
    {
        public long Id { get; set; }
        public Nullable<System.Guid> IdProductTemp { get; set; }
        public string DescriptionTemp { get; set; }
        public int QuantityTemp { get; set; }
        public decimal PurchasePriceTemp { get; set; }
        public decimal SalePriceTemp { get; set; }
        public bool FreeTemp { get; set; }
    }
}
