//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BillDetail = new HashSet<BillDetail>();
            this.Inventory = new HashSet<Inventory>();
            this.RemissionDetail = new HashSet<RemissionDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> IdUnit { get; set; }
        public Nullable<bool> Free { get; set; }
    
        public virtual ICollection<BillDetail> BillDetail { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
        public virtual ICollection<RemissionDetail> RemissionDetail { get; set; }
    }
}
