//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remission
    {
        public Remission()
        {
            this.RemissionDetail = new HashSet<RemissionDetail>();
        }
    
        public System.Guid Id { get; set; }
        public decimal Total { get; set; }
        public long RemissionNumber { get; set; }
        public Nullable<System.Guid> IdClient { get; set; }
        public Nullable<System.DateTime> DateEvent { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<RemissionDetail> RemissionDetail { get; set; }
    }
}
