//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolModule
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdRol { get; set; }
        public Nullable<System.Guid> IdModule { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
