//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturando.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRol = new HashSet<UserRol>();
            this.CashBox = new HashSet<CashBox>();
            this.Bill = new HashSet<Bill>();
            this.Remission = new HashSet<Remission>();
        }
    
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime DateEvent { get; set; }
    
        public virtual ICollection<UserRol> UserRol { get; set; }
        public virtual ICollection<CashBox> CashBox { get; set; }
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual ICollection<Remission> Remission { get; set; }
    }
}
